
services:
  cmdicdn:
    image: huccdn
    container_name: huccdn
    restart: unless-stopped
    volumes:
      - ./js:/usr/share/nginx/html/js
      - ./css:/usr/share/nginx/html/css
    ports:
      - 1016:80
    networks:
      - traefik-public


networks:
  traefik-public:
    external: false