/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ProfilesProfileNameRecordsRecordIdEditRouteImport } from './routes/profiles.$profileName/records/$recordId.edit'
import { Route as ProfilesProfileNameRecordsRecordIdHistoryRouteImport } from './routes/profiles.$profileName/records/$recordId.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesProfileNameRecordsRecordIdEditRoute =
  ProfilesProfileNameRecordsRecordIdEditRouteImport.update({
    id: '/profiles/$profileName/records/$recordId/edit',
    path: '/profiles/$profileName/records/$recordId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfilesProfileNameRecordsRecordIdHistoryRoute =
  ProfilesProfileNameRecordsRecordIdHistoryRouteImport.update({
    id: '/profiles/$profileName/records/$recordId/history',
    path: '/profiles/$profileName/records/$recordId/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRoute
  '/profiles/$profileName/records/$recordId/edit': typeof ProfilesProfileNameRecordsRecordIdEditRoute
  '/profiles/$profileName/records/$recordId/history': typeof ProfilesProfileNameRecordsRecordIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRoute
  '/profiles/$profileName/records/$recordId/edit': typeof ProfilesProfileNameRecordsRecordIdEditRoute
  '/profiles/$profileName/records/$recordId/history': typeof ProfilesProfileNameRecordsRecordIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRoute
  '/profiles/$profileName/records/$recordId/edit': typeof ProfilesProfileNameRecordsRecordIdEditRoute
  '/profiles/$profileName/records/$recordId/history': typeof ProfilesProfileNameRecordsRecordIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/redirect'
    | '/users'
    | '/profiles/$profileName/records/$recordId/edit'
    | '/profiles/$profileName/records/$recordId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/redirect'
    | '/users'
    | '/profiles/$profileName/records/$recordId/edit'
    | '/profiles/$profileName/records/$recordId/history'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/me'
    | '/redirect'
    | '/users'
    | '/profiles/$profileName/records/$recordId/edit'
    | '/profiles/$profileName/records/$recordId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  RedirectRoute: typeof RedirectRoute
  UsersRoute: typeof UsersRoute
  ProfilesProfileNameRecordsRecordIdEditRoute: typeof ProfilesProfileNameRecordsRecordIdEditRoute
  ProfilesProfileNameRecordsRecordIdHistoryRoute: typeof ProfilesProfileNameRecordsRecordIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$profileName/records/$recordId/edit': {
      id: '/profiles/$profileName/records/$recordId/edit'
      path: '/profiles/$profileName/records/$recordId/edit'
      fullPath: '/profiles/$profileName/records/$recordId/edit'
      preLoaderRoute: typeof ProfilesProfileNameRecordsRecordIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$profileName/records/$recordId/history': {
      id: '/profiles/$profileName/records/$recordId/history'
      path: '/profiles/$profileName/records/$recordId/history'
      fullPath: '/profiles/$profileName/records/$recordId/history'
      preLoaderRoute: typeof ProfilesProfileNameRecordsRecordIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  RedirectRoute: RedirectRoute,
  UsersRoute: UsersRoute,
  ProfilesProfileNameRecordsRecordIdEditRoute:
    ProfilesProfileNameRecordsRecordIdEditRoute,
  ProfilesProfileNameRecordsRecordIdHistoryRoute:
    ProfilesProfileNameRecordsRecordIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
